version: '3'
services:
  node:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    environment:
      CONNECTION_STRING: mongodb://mongo:27017/rms
      PORT: 5001
      JWT_SECRET_KEY: THISISJWTTOKENFORTESTING
    depends_on:
      - mongo
  react:
    build:
      context: ./client
      dockerfile: Dockerfile-client
    ports:
      - "5173:5173"
    depends_on:
      - node
  mongo:
    build:
      context: ./server
      dockerfile: Dockerfile-mongo
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: rms
      MONGO_INITDB_ROOT_PASSWORD: admin
      MONGO_INITDB_ROOT_USERNAME: admin
    volumes:
      - mongo_db:/data/db
        
volumes:
  mongo_db:
